### ISSUE TITLE
What about Fxp.sum?

### ISSUE THREAD

**Issue by lpuglia** [francof2a/fxpmath#5]
Hello, do you think it's possible to implement the equivalent of:
https://numpy.org/doc/1.18/reference/generated/numpy.sum.html
for Fxp class? This would be a wrapper of the numpy version called on the internal `ndarray` stored in `val` attribute.

I don't see particular corner cases to test for, it 'should' be pretty straight forward to implement. At the moment I'm very interested in the axis argument.

At the moment I'm using:
``` python
Fxp(np.sum(fxp_object.get_val(), axis=(1,2,3))).like(FORMAT)
```

There are multiple functions that can be wrapped in this way directly from numpy (e.g. `numpy.prod`).

**Comment by francof2a** [comment]
Hello,
Version 0.3.7 was released. In this version, a `sum` function was implemented in **fxpmath.functions**.

It is similar to numpy `sum` but has an extra parameter to defined the output Fxp size. You can find more info in docstring of that function. In the future it would be nice to add as a method, but a good way to do that is using dispatcher; because of that, I didn't prefer to add a method right now.

Here some examples:

```python
vals = np.array([-2, -1, 0, 1, 2, 3, 4])
x = Fxp(vals, True, 16, 2)

y = fxp.sum(x)
y = fxp.sum(x, sizes='same_sizes')
y = fxp.sum(x, sizes='tight_sizes')

z = Fxp(None, True, 16, 4)

y = fxp.sum(x, out=z)
y = fxp.sum(x, dtype=z.dtype)
y = fxp.sum(x, dtype='fxp-s16/2')

vals = np.array([
    [-2, -1, 0], 
    [1, 2, 3]])
x = Fxp(vals, True, 16, 2)
    
y = fxp.sum(x, axis=0)
y = fxp.sum(x, axis=1)
```

Please check if the issue is solved for you.
