### ISSUE TITLE
Numba support?

### ISSUE THREAD

**Issue by fakuivan** [francof2a/fxpmath#72]
Is it possible to integrate Fxp into Numba? Maybe using something like the [`jitclass`](https://numba.pydata.org/numba-doc/latest/user/jitclass.html) decorator

**Comment by francof2a** [comment]
Interesting question!
I think the short answer is **No**. I did some brief test and Fxp does not support `jitclass` decorator. There are a copule of things that Fxp has implemented in order to increase flexibility that wouldn't allow Numba support, but I think it could be a nice feature to implement in the future.
As this functionality was not planned until now, let me move this issue into a **discussion**.
